image: node:22
stages:
  - install
  - build
  - test

# Caching node_modules to avoid re-installing dependencies in every stage
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  image: node:22
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day

build-job:
  stage: build
  image: node:22
  script:
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test-job:
  stage: test
  image: node:22
  script:
    - npm run test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
