<<<<<<< HEAD
image : node:22
stages:
=======
stages:
  - build
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
  - test
  - deploy

variables:
  NODE_ENV: production

before_script:
  - echo "Installing dependencies..."
  - npm install

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm run test
  only:
    - main

<<<<<<< HEAD
=======
build:
  stage: build
  script:
    - echo "Building the project..."
    - npm run build
  only:
    - main
>>>>>>> 8397db2 (Add .gitlab-ci.yml)

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    # Add your deploy commands here, e.g., AWS, Docker
  only:
    - main
