image: node:22
stages:
  - build

  - test
  - deploy

variables:
  NODE_ENV: production

before_script:
  - echo "Installing dependencies..."
  - npm install

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm install
    - npm run test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/