<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
image: node:22
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
image : node:22
>>>>>>> dcfbd1b (Add .gitlab-ci.yml image node version 22)
stages:
  - build
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 858cf21 (Add .gitlab-ci.yml)
=======
>>>>>>> b37803a (Add .gitlab-ci.yml image node version 22)
=======
>>>>>>> 8014825 (Add .gitlab-ci.yml)
=======
=======
>>>>>>> 2e5b7fd (Add .gitlab-ci.yml)
image: node:18 # Base image with Node.js installed

stages:
  - install
=======
stages:
  - build
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
<<<<<<< HEAD
>>>>>>> 2a641a1 (Add .gitlab-ci.yml)
image : node:22
=======
image : node:22
stages:
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
=======
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
image : node:22

stages:
  - build
<<<<<<< HEAD
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
  - test
  - deploy

variables:
  NODE_ENV: production

before_script:
  - echo "Installing dependencies..."
<<<<<<< HEAD
  - npm ci

install:
  stage: install
  script:
    - echo "Installing dependencies..."
    - npm install
=======
  - npm install
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)

>>>>>>> 2e5b7fd (Add .gitlab-ci.yml)
=======
=======
>>>>>>> a177d46 (Add .gitlab-ci.yml)
image: node:22
>>>>>>> d9420ce (Add feature caching in .gitlab-ci.yml)
stages:
  - install
  - build
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 65e263e (Add .gitlab-ci.yml)
=======
=======
image : node:22
stages:
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
>>>>>>> 0b8fcaf (Add .gitlab-ci.yml image node version 22)
  - test

# Caching node_modules to avoid re-installing dependencies in every stage
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  image: node:22
  script:
    - npm install
=======
  - npm install
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm install
    - npm run test
<<<<<<< HEAD
=======
  only:
    - main

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
build:
  stage: build
  image: node:22
  script:
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test-job:
  stage: test
  image: node:22
  script:
<<<<<<< HEAD
<<<<<<< HEAD
    - npm run test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
<<<<<<< HEAD
      - node_modules/
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
=======
>>>>>>> 65e263e (Add .gitlab-ci.yml)
=======
>>>>>>> 0b8fcaf (Add .gitlab-ci.yml image node version 22)
<<<<<<< HEAD
>>>>>>> dcfbd1b (Add .gitlab-ci.yml image node version 22)
=======
=======
>>>>>>> 8ab746c (Add .gitlab-ci.yml)
=======
>>>>>>> 7898957 (Add .gitlab-ci.yml)
=======
>>>>>>> 07b5e32 (Add feature caching in .gitlab-ci.yml)
=======
>>>>>>> b86e844 (Add .gitlab-ci.yml)
>>>>>>> bfc3889 (Add .gitlab-ci.yml)
image: node:18 # Base image with Node.js installed

stages:
  - install
<<<<<<< HEAD
=======
=======
stages:
  - build
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
=======
>>>>>>> b3529be (Add .gitlab-ci.yml)
image : node:22
stages:
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
<<<<<<< HEAD
=======
=======
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
image : node:22

stages:
  - build
<<<<<<< HEAD
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
=======
image : node:22
stages:
>>>>>>> 4c3a3df (Add .gitlab-ci.yml image node version 22)
>>>>>>> 499e212 (Add .gitlab-ci.yml image node version 22)
  - test
  - deploy

variables:
  NODE_ENV: production

before_script:
  - echo "Installing dependencies..."
<<<<<<< HEAD
=======
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 499e212 (Add .gitlab-ci.yml image node version 22)
  - npm ci

install:
  stage: install
  script:
    - echo "Installing dependencies..."
    - npm install

test:
  stage: test
=======
# Caching node_modules to avoid re-installing dependencies in every stage
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  image: node:22
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)
  script:
    - echo "Running tests..."
    - npm run test
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
  only:
    - main
<<<<<<< HEAD
=======
=======
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)

<<<<<<< HEAD
build-job:
  stage: build
  image: node:22
  script:
    - npm run build
<<<<<<< HEAD
>>>>>>> ef103fc (Add .gitlab-ci.yml)

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
=======

>>>>>>> 858cf21 (Add .gitlab-ci.yml)
=======
<<<<<<< HEAD
>>>>>>> b37803a (Add .gitlab-ci.yml image node version 22)
=======
    only:
      - main


>>>>>>> 8014825 (Add .gitlab-ci.yml)
build:
  stage: build
  script:
    - echo "Building the project..."
    - npm run build
  only:
    - main
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
>>>>>>> 15db498 (Add .gitlab-ci.yml image node version 22)

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    # Add your deployment commands here
>>>>>>> 401f503 (Add .gitlab-ci.yml)
<<<<<<< HEAD
=======
=======
=======
    # Add your deploy commands here, e.g., AWS, Docker
<<<<<<< HEAD
  only:
    - main
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 65e263e (Add .gitlab-ci.yml)
=======
=======
>>>>>>> ef103fc (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 7898957 (Add .gitlab-ci.yml)
=======
=======
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test-job:
  stage: test
  image: node:22
  script:
=======
>>>>>>> d9420ce (Add feature caching in .gitlab-ci.yml)
    - npm run test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 07b5e32 (Add feature caching in .gitlab-ci.yml)
=======
=======
=======
image: node:18 # Base image with Node.js installed

stages:
  - install
  - test
  - deploy

variables:
  NODE_ENV: production

before_script:
  - echo "Installing dependencies..."
  - npm ci

install:
  stage: install
  script:
    - echo "Installing dependencies..."
    - npm install
=======
  - npm install
>>>>>>> 4c3a3df (Add .gitlab-ci.yml image node version 22)

=======
image: node:22

stages:
  - test
  - deploy

>>>>>>> fe8149c (Add .gitlab-ci.yml)
test:
  stage: test
  script:
    - echo "Running tests..."
    - npm run test
<<<<<<< HEAD
<<<<<<< HEAD
=======
  only:
    - main
=======

build:
  stage: build
  script:
    - npm run build
>>>>>>> fe8149c (Add .gitlab-ci.yml)

>>>>>>> 4c3a3df (Add .gitlab-ci.yml image node version 22)
=======
>>>>>>> b37803a (Add .gitlab-ci.yml image node version 22)
=======

>>>>>>> 8014825 (Add .gitlab-ci.yml)

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
<<<<<<< HEAD
<<<<<<< HEAD
    # Add your deployment commands here
>>>>>>> 401f503 (Add .gitlab-ci.yml)
>>>>>>> b3529be (Add .gitlab-ci.yml)
>>>>>>> b86e844 (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> bfc3889 (Add .gitlab-ci.yml)
=======
=======
>>>>>>> 9b9e95f (Add .gitlab-ci.yml)
=======
    # Add your deploy commands here, e.g., AWS, Docker
<<<<<<< HEAD
  only:
    - main
>>>>>>> 4c3a3df (Add .gitlab-ci.yml image node version 22)
=======
>>>>>>> fe8149c (Add .gitlab-ci.yml)
=======
=======
    - echo "Deploying the project..."
<<<<<<< HEAD
    # Add your deployment commands here
>>>>>>> 2a641a1 (Add .gitlab-ci.yml)
=======
    # Add your deploy commands here, e.g., AWS, Docker
  only:
    - main
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 65e263e (Add .gitlab-ci.yml)
>>>>>>> 858cf21 (Add .gitlab-ci.yml)
=======
  only:
    - main
>>>>>>> 8014825 (Add .gitlab-ci.yml)
=======
      - node_modules/
>>>>>>> a392ea5 (Add .gitlab-ci.yml)
=======
>>>>>>> 2a641a1 (Add .gitlab-ci.yml)
=======
>>>>>>> d9420ce (Add feature caching in .gitlab-ci.yml)
=======
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)
>>>>>>> 2e5b7fd (Add .gitlab-ci.yml)
