<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
image: node:18 # Base image with Node.js installed

stages:
  - install
=======
stages:
  - build
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
image : node:22
stages:
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
=======
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
image : node:22

stages:
  - build
<<<<<<< HEAD
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
  - test
  - deploy

variables:
  NODE_ENV: production

before_script:
  - echo "Installing dependencies..."
<<<<<<< HEAD
  - npm ci

install:
  stage: install
  script:
    - echo "Installing dependencies..."
    - npm install
=======
  - npm install
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)

=======
image: node:22
stages:
  - install
  - build
  - test

# Caching node_modules to avoid re-installing dependencies in every stage
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  image: node:22
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day

build-job:
  stage: build
  image: node:22
  script:
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test-job:
  stage: test
  image: node:22
  script:
    - npm run test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)
