<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
image: node:22
=======
=======
>>>>>>> 8014825 (Add .gitlab-ci.yml)
image : node:22
>>>>>>> b37803a (Add .gitlab-ci.yml image node version 22)
stages:
  - install
  - build
<<<<<<< HEAD
=======
=======
>>>>>>> 0b8fcaf (Add .gitlab-ci.yml image node version 22)
<<<<<<< HEAD
=======
>>>>>>> 3cc00a9 (Add .gitlab-ci.yml)
=======
>>>>>>> 8ab746c (Add .gitlab-ci.yml)
=======
>>>>>>> 7898957 (Add .gitlab-ci.yml)
=======
>>>>>>> 07b5e32 (Add feature caching in .gitlab-ci.yml)
=======
>>>>>>> b86e844 (Add .gitlab-ci.yml)
=======
>>>>>>> b37803a (Add .gitlab-ci.yml image node version 22)
<<<<<<< HEAD
image: node:18 # Base image with Node.js installed

stages:
  - install
=======
stages:
  - build
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 65e263e (Add .gitlab-ci.yml)
=======
=======
<<<<<<< HEAD
=======
>>>>>>> b3529be (Add .gitlab-ci.yml)
=======
>>>>>>> 858cf21 (Add .gitlab-ci.yml)
image : node:22
stages:
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
<<<<<<< HEAD
>>>>>>> 0b8fcaf (Add .gitlab-ci.yml image node version 22)
=======
=======
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
image : node:22

stages:
  - build
<<<<<<< HEAD
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 3cc00a9 (Add .gitlab-ci.yml)
=======
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
>>>>>>> 8ab746c (Add .gitlab-ci.yml)
=======
image : node:22
stages:
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
>>>>>>> 0b8fcaf (Add .gitlab-ci.yml image node version 22)
>>>>>>> b37803a (Add .gitlab-ci.yml image node version 22)
=======
>>>>>>> 8014825 (Add .gitlab-ci.yml)
  - test

# Caching node_modules to avoid re-installing dependencies in every stage
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  image: node:22
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day

<<<<<<< HEAD

<<<<<<< HEAD
build-job:
  stage: build
  image: node:22
=======
=======
image: node:22

=======
image : node:22
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)
stages:
  - install
  - build
=======
<<<<<<< HEAD
image: node:18 # Base image with Node.js installed

stages:
  - install
=======
stages:
  - build
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
>>>>>>> 65e263e (Add .gitlab-ci.yml)
  - test

<<<<<<< HEAD
>>>>>>> ef103fc (Add .gitlab-ci.yml)
test:
  stage: test
<<<<<<< HEAD
>>>>>>> 7898957 (Add .gitlab-ci.yml)
  script:
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test-job:
  stage: test
  image: node:22
  script:
<<<<<<< HEAD
=======
    - echo "Running tests..."
<<<<<<< HEAD
<<<<<<< HEAD
    - npm install
>>>>>>> e3fe733 (Add .gitlab-ci.yml)
=======
    - npm install
>>>>>>> 5e7a653 (Fixed install issue)
=======
=======
# Caching node_modules to avoid re-installing dependencies in every stage
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

<<<<<<< HEAD
install-dependencies:
=======
before_script:
  - echo "Installing dependencies..."
<<<<<<< HEAD
  - npm ci

install:
>>>>>>> 65e263e (Add .gitlab-ci.yml)
  stage: install
  image: node:22
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)
  script:
    - npm install
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 07b5e32 (Add feature caching in .gitlab-ci.yml)
    - npm run test
<<<<<<< HEAD
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
=======
=======
    - npm run test
<<<<<<< HEAD
>>>>>>> 7898957 (Add .gitlab-ci.yml)
<<<<<<< HEAD
=======
  only:
    - main
=======
=======
=======
>>>>>>> 858cf21 (Add .gitlab-ci.yml)
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day
<<<<<<< HEAD
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)
=======
=======
=======
  - npm install
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
>>>>>>> 65e263e (Add .gitlab-ci.yml)
>>>>>>> 858cf21 (Add .gitlab-ci.yml)

=======
>>>>>>> a392ea5 (Add .gitlab-ci.yml)
build-job:
  stage: build
  image: node:22
  script:
    - npm run build
<<<<<<< HEAD
>>>>>>> ef103fc (Add .gitlab-ci.yml)

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
build:
  stage: build
  script:
    - echo "Building the project..."
    - npm run build
  only:
    - main
<<<<<<< HEAD
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
=======
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
>>>>>>> 8e0480a (Add .gitlab-ci.yml)

=======
>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
<<<<<<< HEAD
    # Add your deployment commands here
=======
    # Add your deploy commands here, e.g., AWS, Docker
<<<<<<< HEAD
  only:
    - main
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 65e263e (Add .gitlab-ci.yml)
=======
=======
>>>>>>> ef103fc (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 7898957 (Add .gitlab-ci.yml)
=======
=======
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test-job:
  stage: test
  image: node:22
  script:
    - npm run test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
<<<<<<< HEAD
      - node_modules/
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 07b5e32 (Add feature caching in .gitlab-ci.yml)
=======
=======
=======
image: node:18 # Base image with Node.js installed

stages:
  - install
=======
image : node:22
stages:
>>>>>>> 4c3a3df (Add .gitlab-ci.yml image node version 22)
=======
=======

>>>>>>> d86ace1 (Add .gitlab-ci.yml)
image : node:22

stages:
  - build
<<<<<<< HEAD
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
>>>>>>> 0d2e058 (Add .gitlab-ci.yml)
=======

>>>>>>> d86ace1 (Add .gitlab-ci.yml)
  - test
  - deploy

variables:
  NODE_ENV: production

before_script:
  - echo "Installing dependencies..."
<<<<<<< HEAD
  - npm ci

install:
  stage: install
  script:
    - echo "Installing dependencies..."
    - npm install
=======
  - npm install
>>>>>>> 4c3a3df (Add .gitlab-ci.yml image node version 22)

=======
image: node:22

=======
image : node:22
>>>>>>> f8d76df (Add feature caching in .gitlab-ci.yml)
stages:
  - install
  - build
  - test

<<<<<<< HEAD
>>>>>>> fe8149c (Add .gitlab-ci.yml)
test:
  stage: test
=======
# Caching node_modules to avoid re-installing dependencies in every stage
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  image: node:22
>>>>>>> f8d76df (Add feature caching in .gitlab-ci.yml)
  script:
    - npm install
<<<<<<< HEAD
    - npm run test
<<<<<<< HEAD
=======
=======
>>>>>>> 858cf21 (Add .gitlab-ci.yml)
<<<<<<< HEAD
=======
  only:
    - main
<<<<<<< HEAD
=======
=======
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day
>>>>>>> f8d76df (Add feature caching in .gitlab-ci.yml)

<<<<<<< HEAD
build-job:
  stage: build
  image: node:22
  script:
    - npm run build
<<<<<<< HEAD
>>>>>>> fe8149c (Add .gitlab-ci.yml)

<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 4c3a3df (Add .gitlab-ci.yml image node version 22)
=======
<<<<<<< HEAD
=======
=======

>>>>>>> 858cf21 (Add .gitlab-ci.yml)
=======
<<<<<<< HEAD
>>>>>>> b37803a (Add .gitlab-ci.yml image node version 22)
=======
    only:
      - main


>>>>>>> 8014825 (Add .gitlab-ci.yml)
build:
  stage: build
  script:
    - echo "Building the project..."
    - npm run build
  only:
    - main
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
>>>>>>> 0d2e058 (Add .gitlab-ci.yml)

=======
>>>>>>> d86ace1 (Add .gitlab-ci.yml)
=======
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
=======

>>>>>>> 8014825 (Add .gitlab-ci.yml)

>>>>>>> 858cf21 (Add .gitlab-ci.yml)
deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
<<<<<<< HEAD
<<<<<<< HEAD
    # Add your deployment commands here
<<<<<<< HEAD
>>>>>>> 401f503 (Add .gitlab-ci.yml)
>>>>>>> b3529be (Add .gitlab-ci.yml)
>>>>>>> b86e844 (Add .gitlab-ci.yml)
=======
>>>>>>> 9b9e95f (Add .gitlab-ci.yml)
=======
    # Add your deploy commands here, e.g., AWS, Docker
<<<<<<< HEAD
  only:
    - main
>>>>>>> 4c3a3df (Add .gitlab-ci.yml image node version 22)
=======
>>>>>>> fe8149c (Add .gitlab-ci.yml)
=======
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test-job:
  stage: test
  image: node:22
  script:
    - npm run test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
>>>>>>> f8d76df (Add feature caching in .gitlab-ci.yml)
=======
=======
    # Add your deploy commands here, e.g., AWS, Docker
  only:
    - main
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
>>>>>>> 65e263e (Add .gitlab-ci.yml)
>>>>>>> 858cf21 (Add .gitlab-ci.yml)
=======
  only:
    - main
>>>>>>> 8014825 (Add .gitlab-ci.yml)
=======
      - node_modules/
>>>>>>> a392ea5 (Add .gitlab-ci.yml)
