<<<<<<< HEAD
image: node:22
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
image : node:22
>>>>>>> dcfbd1b (Add .gitlab-ci.yml image node version 22)
stages:
  - build
  - test

# Caching node_modules to avoid re-installing dependencies in every stage
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  image: node:22
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day

build-job:
  stage: build
  image: node:22
  script:
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test-job:
  stage: test
  image: node:22
  script:
    - npm run test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
=======
<<<<<<< HEAD
=======
=======
>>>>>>> 65e263e (Add .gitlab-ci.yml)
=======
>>>>>>> 0b8fcaf (Add .gitlab-ci.yml image node version 22)
>>>>>>> dcfbd1b (Add .gitlab-ci.yml image node version 22)
image: node:18 # Base image with Node.js installed

stages:
  - install
<<<<<<< HEAD
=======
=======
stages:
  - build
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
image : node:22
stages:
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
  - test
  - deploy

variables:
  NODE_ENV: production

before_script:
  - echo "Installing dependencies..."
  - npm ci

install:
  stage: install
  script:
    - echo "Installing dependencies..."
    - npm install

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm install
    - npm run test
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
  only:
    - main

<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
build:
  stage: build
  script:
    - echo "Building the project..."
    - npm run build
  only:
    - main
<<<<<<< HEAD
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    # Add your deployment commands here
>>>>>>> 401f503 (Add .gitlab-ci.yml)
