<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
image: node:22
stages:
  - install
  - build
=======
=======
>>>>>>> 0b8fcaf (Add .gitlab-ci.yml image node version 22)
=======
>>>>>>> 3cc00a9 (Add .gitlab-ci.yml)
=======
>>>>>>> 8ab746c (Add .gitlab-ci.yml)
=======
>>>>>>> 7898957 (Add .gitlab-ci.yml)
=======
>>>>>>> 07b5e32 (Add feature caching in .gitlab-ci.yml)
=======
>>>>>>> b86e844 (Add .gitlab-ci.yml)
<<<<<<< HEAD
image: node:18 # Base image with Node.js installed

stages:
  - install
=======
stages:
  - build
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 65e263e (Add .gitlab-ci.yml)
=======
=======
=======
>>>>>>> b3529be (Add .gitlab-ci.yml)
image : node:22
stages:
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
<<<<<<< HEAD
>>>>>>> 0b8fcaf (Add .gitlab-ci.yml image node version 22)
=======
=======
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
image : node:22

stages:
  - build
<<<<<<< HEAD
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 3cc00a9 (Add .gitlab-ci.yml)
=======
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
>>>>>>> 8ab746c (Add .gitlab-ci.yml)
  - test

# Caching node_modules to avoid re-installing dependencies in every stage
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

<<<<<<< HEAD
install-dependencies:
=======
before_script:
  - echo "Installing dependencies..."
<<<<<<< HEAD
  - npm ci

install:
>>>>>>> 65e263e (Add .gitlab-ci.yml)
  stage: install
  image: node:22
  script:
    - npm install
<<<<<<< HEAD
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day
=======
=======
  - npm install
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
>>>>>>> 65e263e (Add .gitlab-ci.yml)

<<<<<<< HEAD
build-job:
  stage: build
  image: node:22
=======
=======
image: node:22

=======
image : node:22
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)
stages:
  - install
  - build
  - test

<<<<<<< HEAD
>>>>>>> ef103fc (Add .gitlab-ci.yml)
test:
  stage: test
<<<<<<< HEAD
>>>>>>> 7898957 (Add .gitlab-ci.yml)
  script:
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test-job:
  stage: test
  image: node:22
  script:
<<<<<<< HEAD
=======
    - echo "Running tests..."
<<<<<<< HEAD
<<<<<<< HEAD
    - npm install
>>>>>>> e3fe733 (Add .gitlab-ci.yml)
=======
    - npm install
>>>>>>> 5e7a653 (Fixed install issue)
=======
=======
# Caching node_modules to avoid re-installing dependencies in every stage
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  image: node:22
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)
  script:
    - npm install
<<<<<<< HEAD
>>>>>>> 07b5e32 (Add feature caching in .gitlab-ci.yml)
    - npm run test
<<<<<<< HEAD
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
=======
=======
    - npm run test
<<<<<<< HEAD
>>>>>>> 7898957 (Add .gitlab-ci.yml)
<<<<<<< HEAD
=======
  only:
    - main
=======
=======
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)

build-job:
  stage: build
  image: node:22
  script:
    - npm run build
<<<<<<< HEAD
>>>>>>> ef103fc (Add .gitlab-ci.yml)

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
build:
  stage: build
  script:
    - echo "Building the project..."
    - npm run build
  only:
    - main
<<<<<<< HEAD
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
=======
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
>>>>>>> 8e0480a (Add .gitlab-ci.yml)

=======
>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
<<<<<<< HEAD
    # Add your deployment commands here
=======
    # Add your deploy commands here, e.g., AWS, Docker
<<<<<<< HEAD
  only:
    - main
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 65e263e (Add .gitlab-ci.yml)
=======
=======
>>>>>>> ef103fc (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 7898957 (Add .gitlab-ci.yml)
=======
=======
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test-job:
  stage: test
  image: node:22
  script:
    - npm run test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
<<<<<<< HEAD
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 07b5e32 (Add feature caching in .gitlab-ci.yml)
=======
=======
=======
image: node:18 # Base image with Node.js installed

stages:
  - install
  - test
  - deploy

variables:
  NODE_ENV: production

before_script:
  - echo "Installing dependencies..."
  - npm ci

install:
  stage: install
  script:
    - echo "Installing dependencies..."
    - npm install

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm run test

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    # Add your deployment commands here
>>>>>>> 401f503 (Add .gitlab-ci.yml)
>>>>>>> b3529be (Add .gitlab-ci.yml)
>>>>>>> b86e844 (Add .gitlab-ci.yml)
