<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 2e5b7fd (Add .gitlab-ci.yml)
image: node:18 # Base image with Node.js installed

stages:
  - install
=======
stages:
  - build
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
image : node:22
<<<<<<< HEAD
=======
stages:
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
=======
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
image : node:22

stages:
  - build
<<<<<<< HEAD
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
  - test
  - deploy

variables:
  NODE_ENV: production

before_script:
  - echo "Installing dependencies..."
<<<<<<< HEAD
  - npm ci

install:
  stage: install
  script:
    - echo "Installing dependencies..."
    - npm install
=======
  - npm install
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)

=======
=======
>>>>>>> a177d46 (Add .gitlab-ci.yml)
image: node:22
>>>>>>> 2e5b7fd (Add .gitlab-ci.yml)
stages:
  - install
  - build
=======
=======
>>>>>>> 0b8fcaf (Add .gitlab-ci.yml image node version 22)
<<<<<<< HEAD
image: node:18 # Base image with Node.js installed

stages:
  - install
=======
stages:
  - install
  - build
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 65e263e (Add .gitlab-ci.yml)
=======
=======
image : node:22
stages:
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
>>>>>>> 0b8fcaf (Add .gitlab-ci.yml image node version 22)
  - test

# Caching node_modules to avoid re-installing dependencies in every stage
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  image: node:22
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day

build-job:
  stage: build
  image: node:22
  script:
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test-job:
  stage: test
  image: node:22
  script:
<<<<<<< HEAD
    - echo "Deploying the project..."
<<<<<<< HEAD
    # Add your deployment commands here
=======
    # Add your deploy commands here, e.g., AWS, Docker
  only:
    - main

=======
    - npm run test
<<<<<<< HEAD
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
<<<<<<< HEAD
>>>>>>> 9ca94b1 (Add feature caching in .gitlab-ci.yml)
>>>>>>> 2e5b7fd (Add .gitlab-ci.yml)
=======
>>>>>>> a177d46 (Add .gitlab-ci.yml)
=======
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    # Add your deploy commands here, e.g., AWS, Docker
  only:
    - main
>>>>>>> 902e036 (Add .gitlab-ci.yml)
