<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
image: node:18 # Base image with Node.js installed

stages:
  - install
=======
stages:
  - build
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
image : node:22
stages:
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
=======
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
image : node:22

stages:
  - build
<<<<<<< HEAD
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
=======

>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
  - test
  - deploy

variables:
  NODE_ENV: production

before_script:
  - echo "Installing dependencies..."
<<<<<<< HEAD
  - npm ci

install:
  stage: install
  script:
    - echo "Installing dependencies..."
    - npm install
=======
  - npm install
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm run test
<<<<<<< HEAD
=======
  only:
    - main

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
build:
  stage: build
  script:
    - echo "Building the project..."
    - npm run build
  only:
    - main
<<<<<<< HEAD
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
=======
>>>>>>> 8397db2 (Add .gitlab-ci.yml)
>>>>>>> 8e0480a (Add .gitlab-ci.yml)

=======
>>>>>>> 0d9bf5a (Add .gitlab-ci.yml)
deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
<<<<<<< HEAD
    # Add your deployment commands here
=======
    # Add your deploy commands here, e.g., AWS, Docker
  only:
    - main
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
