<<<<<<< HEAD
<<<<<<< HEAD
image : node:22
stages:
  - install
  - build
=======
=======
>>>>>>> 0b8fcaf (Add .gitlab-ci.yml image node version 22)
<<<<<<< HEAD
image: node:18 # Base image with Node.js installed

stages:
  - install
=======
stages:
  - build
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
<<<<<<< HEAD
>>>>>>> 65e263e (Add .gitlab-ci.yml)
=======
=======
image : node:22
stages:
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)
>>>>>>> 0b8fcaf (Add .gitlab-ci.yml image node version 22)
  - test

# Caching node_modules to avoid re-installing dependencies in every stage
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
=======
before_script:
  - echo "Installing dependencies..."
<<<<<<< HEAD
  - npm ci

install:
>>>>>>> 65e263e (Add .gitlab-ci.yml)
  stage: install
  image: node:22
  script:
    - npm install
<<<<<<< HEAD
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day
=======
=======
  - npm install
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
>>>>>>> 65e263e (Add .gitlab-ci.yml)

build-job:
  stage: build
  image: node:22
  script:
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test-job:
  stage: test
  image: node:22
  script:
    - npm run test
<<<<<<< HEAD
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    only:
      - main

<<<<<<< HEAD
build:
  stage: build
  script:
    - echo "Building the project..."
    - npm run build
  only:
    - main
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
>>>>>>> 564fb52 (Add .gitlab-ci.yml image node version 22)

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
  only:
    - main
