image: node:22

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm run test

build:
  stage: build
  script:
    - npm run build


deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    # Add your deploy commands here, e.g., AWS, Docker
