<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
image: node:18 # Base image with Node.js installed

stages:
  - install
=======
stages:
  - build
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
=======
image : node:22
stages:
  - install
  - build
  - test

# Caching node_modules to avoid re-installing dependencies in every stage
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  image: node:22
  script:
    - npm install
=======
  - npm install
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm install
    - npm run test
<<<<<<< HEAD
=======
  only:
    - main

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 8e0480a (Add .gitlab-ci.yml)
build:
  stage: build
  image: node:22
  script:
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test-job:
  stage: test
  image: node:22
  script:
    - echo "Deploying the project..."
<<<<<<< HEAD
    # Add your deployment commands here
=======
    # Add your deploy commands here, e.g., AWS, Docker
  only:
    - main
>>>>>>> 4ee7531 (Add .gitlab-ci.yml)
